[target.aarch64-unknown-none]
linker = "C:\\Program Files\\Microsoft Visual Studio\\18\\Community\\VC\\Tools\\Llvm\\bin\\ld.lld.exe"
rustflags = ["-C", "link-arg=-TD:\\WorkSpace\\SysemDev\\auraos\\kernel\\aarch64-qemu.ld"]
